name: Deploy para Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar clicando num botão

jobs:
  deploy:
    name: Build e Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy no Fly
        working-directory: ./SindRelatorios
        run: flyctl deploy --local-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
